import type { CompanyEvent, EventType } from "@/lib/types";

export const eventTypes: EventType[] = ["Meeting", "Training", "Holiday", "Company Event", "Festival", "Announcement"];

export const seedEvents: CompanyEvent[] = [
  {
    id: "evt-1",
    title: "All Hands — Q2 Review",
    description: "Company-wide town hall covering Q2 performance and roadmap for the next quarter.",
    type: "Company Event",
    startDate: "2024-07-05",
    endDate: "2024-07-05",
    startTime: "16:00",
    endTime: "17:00",
    location: "Noida HQ — Main Auditorium",
    siteId: "site-1",
    roleIds: [],
    status: "Scheduled",
    createdBy: "Ganesh Pandey",
    createdOn: "2024-06-10",
  },
  {
    id: "evt-2",
    title: "Engineering Sprint Planning",
    description: "Bi-weekly sprint planning for the Product Engineering team.",
    type: "Meeting",
    startDate: "2024-06-24",
    endDate: "2024-06-24",
    startTime: "10:00",
    endTime: "11:30",
    location: "Noida HQ — Engineering Bay",
    siteId: "site-1",
    roleIds: ["role-department-head", "role-manager", "role-employee"],
    status: "Scheduled",
    createdBy: "Rohit Sharma",
    createdOn: "2024-06-15",
  },
  {
    id: "evt-3",
    title: "POSH Awareness Training",
    description: "Mandatory annual compliance training for all employees.",
    type: "Training",
    startDate: "2024-07-15",
    endDate: "2024-07-15",
    startTime: "14:00",
    endTime: "16:00",
    location: "Virtual — Zoom",
    roleIds: [],
    status: "Scheduled",
    createdBy: "Neha Verma",
    createdOn: "2024-06-01",
  },
  {
    id: "evt-4",
    title: "Independence Day",
    description: "National holiday — office closed.",
    type: "Holiday",
    startDate: "2024-08-15",
    endDate: "2024-08-15",
    location: "All Offices",
    roleIds: [],
    status: "Scheduled",
    createdBy: "Neha Verma",
    createdOn: "2024-01-05",
  },
  {
    id: "evt-5",
    title: "HR & Finance Leadership Sync",
    description: "Monthly sync between HR and Finance leadership on headcount and cost planning.",
    type: "Meeting",
    startDate: "2024-06-28",
    endDate: "2024-06-28",
    startTime: "15:00",
    endTime: "16:00",
    location: "Noida HQ — Conference Room 2",
    siteId: "site-1",
    roleIds: ["role-hr-admin", "role-hr-manager", "role-payroll-admin", "role-finance"],
    status: "Scheduled",
    createdBy: "Amit Kumar",
    createdOn: "2024-06-12",
  },
  {
    id: "evt-6",
    title: "Diwali Celebration",
    description: "Office-wide Diwali celebration with games, food and gifting.",
    type: "Festival",
    startDate: "2024-11-01",
    endDate: "2024-11-01",
    startTime: "17:00",
    endTime: "20:00",
    location: "All Offices",
    roleIds: [],
    status: "Scheduled",
    createdBy: "Ganesh Pandey",
    createdOn: "2024-05-20",
  },
];
