import type { ExpenseAuditEntry, ExpenseCategory, ExpenseClaim, TravelRequest } from "@/lib/types";

export const expenseCategories: ExpenseCategory[] = [
  "Travel",
  "Accommodation",
  "Food",
  "Fuel",
  "Internet & Phone",
  "Client Entertainment",
  "Other",
];

export const expenseCategoryConfig: Record<ExpenseCategory, { claimLimit: number; requiresReceipt: boolean }> = {
  Travel: { claimLimit: 5000, requiresReceipt: true },
  Accommodation: { claimLimit: 8000, requiresReceipt: true },
  Food: { claimLimit: 1500, requiresReceipt: true },
  Fuel: { claimLimit: 3000, requiresReceipt: true },
  "Internet & Phone": { claimLimit: 1000, requiresReceipt: false },
  "Client Entertainment": { claimLimit: 5000, requiresReceipt: true },
  Other: { claimLimit: 2000, requiresReceipt: false },
};

export const seedTravelRequests: TravelRequest[] = [
  {
    id: "tr-1",
    employeeId: "EMP002",
    employee: "Rohit Sharma",
    purpose: "Client demo at Bangalore office",
    destination: "Bangalore",
    mode: "Flight",
    fromDate: "2024-06-20",
    toDate: "2024-06-22",
    estimatedCost: 18000,
    status: "Approved",
    siteId: "site-1",
    appliedOn: "2024-06-05",
    approverId: "EMP001",
    approverName: "Ganesh Pandey",
    decidedOn: "2024-06-06",
  },
  {
    id: "tr-2",
    employeeId: "EMP009",
    employee: "Anjali Kumari",
    purpose: "Campus recruitment drive",
    destination: "Pune",
    mode: "Train",
    fromDate: "2024-06-25",
    toDate: "2024-06-26",
    estimatedCost: 6000,
    status: "Pending",
    siteId: "site-4",
    appliedOn: "2024-06-15",
  },
  {
    id: "tr-3",
    employeeId: "EMP006",
    employee: "Vikram Desai",
    purpose: "Data center audit",
    destination: "Chennai",
    mode: "Flight",
    fromDate: "2024-05-10",
    toDate: "2024-05-12",
    estimatedCost: 22000,
    status: "Completed",
    siteId: "site-2",
    appliedOn: "2024-04-28",
    approverId: "EMP002",
    approverName: "Rohit Sharma",
    decidedOn: "2024-04-29",
  },
  {
    id: "tr-4",
    employeeId: "EMP005",
    employee: "Sneha Kapoor",
    purpose: "HR conference",
    destination: "Mumbai",
    mode: "Cab",
    fromDate: "2024-06-18",
    toDate: "2024-06-19",
    estimatedCost: 4000,
    status: "Rejected",
    siteId: "site-3",
    appliedOn: "2024-06-10",
    approverId: "EMP004",
    approverName: "Neha Verma",
    decisionReason: "Budget for this quarter is already allocated — please resubmit for Q3.",
    decidedOn: "2024-06-11",
  },
];

let itemSeq = 0;
function item(date: string, category: ExpenseCategory, amount: number, description: string, hasReceipt: boolean, overLimitNote?: string) {
  itemSeq += 1;
  return { id: `exi-seed-${itemSeq}`, date, category, amount, description, hasReceipt, overLimitNote };
}

export const seedExpenseClaims: ExpenseClaim[] = [
  {
    id: "ec-1",
    employeeId: "EMP002",
    employee: "Rohit Sharma",
    title: "Bangalore Client Visit",
    travelRequestId: "tr-1",
    items: [
      item("2024-06-20", "Travel", 15000, "Round-trip flight to Bangalore", true, "Client-visit fare, pre-approved by manager"),
      item("2024-06-21", "Accommodation", 7000, "Hotel stay (2 nights)", true),
      item("2024-06-21", "Food", 1200, "Meals during trip", true),
    ],
    totalAmount: 23200,
    status: "Reimbursed",
    siteId: "site-1",
    submittedOn: "2024-06-23",
    managerId: "EMP001",
    managerName: "Ganesh Pandey",
    managerDecisionReason: "Approved",
    managerDecidedOn: "2024-06-24",
    financeName: "Amit Kumar",
    financeDecisionReason: "Approved for reimbursement",
    financeDecidedOn: "2024-06-25",
    reimbursedOn: "2024-06-28",
    reimbursementReference: "NEFT-EXP-0628",
  },
  {
    id: "ec-2",
    employeeId: "EMP006",
    employee: "Vikram Desai",
    title: "Chennai Data Center Audit",
    travelRequestId: "tr-3",
    items: [
      item("2024-05-10", "Travel", 20000, "Short-notice flight to Chennai", true, "Approved exception — audit travel booked on short notice"),
      item("2024-05-11", "Accommodation", 6000, "Hotel stay (1 night)", true),
      item("2024-05-11", "Food", 900, "Meals during trip", true),
    ],
    totalAmount: 26900,
    status: "Finance Approved",
    siteId: "site-2",
    submittedOn: "2024-05-13",
    managerId: "EMP002",
    managerName: "Rohit Sharma",
    managerDecisionReason: "Approved",
    managerDecidedOn: "2024-05-14",
    financeName: "Amit Kumar",
    financeDecisionReason: "Approved — pending next reimbursement run",
    financeDecidedOn: "2024-05-16",
  },
  {
    id: "ec-3",
    employeeId: "EMP009",
    employee: "Anjali Kumari",
    title: "Local Client Meetings",
    items: [
      item("2024-06-07", "Fuel", 800, "Fuel for client visits", true),
      item("2024-06-08", "Food", 350, "Working lunch", true),
    ],
    totalAmount: 1150,
    status: "Submitted",
    siteId: "site-4",
    submittedOn: "2024-06-08",
  },
  {
    id: "ec-4",
    employeeId: "EMP005",
    employee: "Sneha Kapoor",
    title: "Office Internet Reimbursement",
    items: [item("2024-05-31", "Internet & Phone", 999, "Monthly broadband bill", false)],
    totalAmount: 999,
    status: "Manager Approved",
    siteId: "site-3",
    submittedOn: "2024-06-01",
    managerId: "EMP004",
    managerName: "Neha Verma",
    managerDecisionReason: "Approved",
    managerDecidedOn: "2024-06-02",
  },
  {
    id: "ec-5",
    employeeId: "EMP003",
    employee: "Priya Singh",
    title: "Team Lunch — Client Entertainment",
    items: [item("2024-05-19", "Client Entertainment", 6500, "Lunch with client delegation (8 attendees)", true, "Larger group than usual — 8 client attendees")],
    totalAmount: 6500,
    status: "Rejected",
    siteId: "site-2",
    submittedOn: "2024-05-20",
    managerId: "EMP002",
    managerName: "Rohit Sharma",
    managerDecisionReason: "Please get prior approval for entertainment expenses above ₹5,000 next time.",
    managerDecidedOn: "2024-05-21",
  },
  {
    id: "ec-6",
    employeeId: "EMP007",
    employee: "Amit Kumar",
    title: "May Fuel & Local Travel",
    items: [
      item("2024-05-15", "Fuel", 1200, "Fuel for site visits", true),
      item("2024-05-18", "Other", 300, "Parking & tolls", false),
    ],
    totalAmount: 1500,
    status: "Draft",
    siteId: "site-1",
  },
];

export const seedExpenseAudit: ExpenseAuditEntry[] = [
  { id: "exp-evt-1", refId: "ec-1", employeeName: "Rohit Sharma", action: "reimbursed", actorName: "Amit Kumar", detail: "Claim reimbursed — ref NEFT-EXP-0628", timestamp: "2024-06-28T09:00:00.000Z" },
  { id: "exp-evt-2", refId: "ec-2", employeeName: "Vikram Desai", action: "finance_approved", actorName: "Amit Kumar", detail: "Finance approved — pending reimbursement run", timestamp: "2024-05-16T09:00:00.000Z" },
  { id: "exp-evt-3", refId: "ec-5", employeeName: "Priya Singh", action: "manager_rejected", actorName: "Rohit Sharma", detail: "Claim rejected — entertainment spend needs prior approval above ₹5,000", timestamp: "2024-05-21T09:00:00.000Z" },
  { id: "exp-evt-4", refId: "tr-4", employeeName: "Sneha Kapoor", action: "travel_decided", actorName: "Neha Verma", detail: "Travel request rejected — budget already allocated this quarter", timestamp: "2024-06-11T09:00:00.000Z" },
];
