import type { EmployeeLoan, LoanType, TaxDeclaration } from "@/lib/types";

export const loanTypes: LoanType[] = ["Salary Advance", "Personal Loan", "Vehicle Loan", "Home Loan"];

/** Simple flat max-months guide shown in the Apply for Loan form — not a hard validation rule. */
export const loanTenureGuide: Record<LoanType, number> = {
  "Salary Advance": 3,
  "Personal Loan": 24,
  "Vehicle Loan": 48,
  "Home Loan": 120,
};

export const seedEmployeeLoans: EmployeeLoan[] = [
  {
    id: "loan-1",
    employeeId: "EMP002",
    employee: "Rohit Sharma",
    type: "Personal Loan",
    principalAmount: 150000,
    emiAmount: 7500,
    tenureMonths: 20,
    outstandingAmount: 150000,
    status: "Pending",
    reason: "Home renovation",
    siteId: "site-1",
    appliedOn: "2024-06-10",
  },
  {
    id: "loan-2",
    employeeId: "EMP003",
    employee: "Priya Singh",
    type: "Salary Advance",
    principalAmount: 50000,
    emiAmount: 16667,
    tenureMonths: 3,
    outstandingAmount: 16667,
    status: "Active",
    reason: "Medical emergency",
    siteId: "site-2",
    appliedOn: "2024-03-01",
    approverId: "EMP002",
    approverName: "Rohit Sharma",
    decidedOn: "2024-03-02",
  },
  {
    id: "loan-3",
    employeeId: "EMP006",
    employee: "Vikram Desai",
    type: "Vehicle Loan",
    principalAmount: 400000,
    emiAmount: 9500,
    tenureMonths: 42,
    outstandingAmount: 342000,
    status: "Active",
    reason: "Two-wheeler purchase",
    siteId: "site-2",
    appliedOn: "2024-01-15",
    approverId: "EMP002",
    approverName: "Rohit Sharma",
    decidedOn: "2024-01-18",
  },
  {
    id: "loan-4",
    employeeId: "EMP009",
    employee: "Anjali Kumari",
    type: "Salary Advance",
    principalAmount: 30000,
    emiAmount: 15000,
    tenureMonths: 2,
    outstandingAmount: 30000,
    status: "Pending",
    reason: "Family function",
    siteId: "site-4",
    appliedOn: "2024-06-18",
  },
  {
    id: "loan-5",
    employeeId: "EMP005",
    employee: "Sneha Kapoor",
    type: "Personal Loan",
    principalAmount: 80000,
    emiAmount: 6667,
    tenureMonths: 12,
    outstandingAmount: 0,
    status: "Closed",
    reason: "Debt consolidation",
    siteId: "site-3",
    appliedOn: "2023-05-01",
    approverId: "EMP004",
    approverName: "Neha Verma",
    decidedOn: "2023-05-03",
  },
];

export const seedTaxDeclarations: TaxDeclaration[] = [
  {
    id: "tax-1",
    employeeId: "EMP001",
    employee: "Ganesh Pandey",
    financialYear: "2024-25",
    regime: "New Regime",
    section80C: 0,
    section80D: 0,
    hraExemptionClaimed: 0,
    otherExemptions: 0,
    status: "Verified",
    siteId: "site-1",
    submittedOn: "2024-04-10",
    verifiedBy: "Amit Kumar",
    verifiedOn: "2024-04-12",
  },
  {
    id: "tax-2",
    employeeId: "EMP002",
    employee: "Rohit Sharma",
    financialYear: "2024-25",
    regime: "Old Regime",
    section80C: 150000,
    section80D: 25000,
    hraExemptionClaimed: 96000,
    otherExemptions: 0,
    status: "Verified",
    siteId: "site-1",
    submittedOn: "2024-04-15",
    verifiedBy: "Amit Kumar",
    verifiedOn: "2024-04-18",
  },
  {
    id: "tax-3",
    employeeId: "EMP003",
    employee: "Priya Singh",
    financialYear: "2024-25",
    regime: "Old Regime",
    section80C: 90000,
    section80D: 12000,
    hraExemptionClaimed: 120000,
    otherExemptions: 5000,
    status: "Submitted",
    siteId: "site-2",
    submittedOn: "2024-05-02",
  },
  {
    id: "tax-4",
    employeeId: "EMP004",
    employee: "Neha Verma",
    financialYear: "2024-25",
    regime: "New Regime",
    section80C: 0,
    section80D: 0,
    hraExemptionClaimed: 0,
    otherExemptions: 0,
    status: "Draft",
    siteId: "site-1",
  },
  {
    id: "tax-5",
    employeeId: "EMP007",
    employee: "Amit Kumar",
    financialYear: "2024-25",
    regime: "Old Regime",
    section80C: 150000,
    section80D: 50000,
    hraExemptionClaimed: 0,
    otherExemptions: 20000,
    status: "Rejected",
    siteId: "site-1",
    submittedOn: "2024-04-20",
    decisionReason: "Section 80D amount exceeds the eligible limit for the declared age bracket — please attach proof or revise.",
  },
];
