import type { AttendanceRegularization } from "@/lib/types";

export const seedRegularizations: AttendanceRegularization[] = [
  {
    id: "reg-1",
    employeeId: "EMP002",
    employee: "Rohit Sharma",
    date: "2024-06-18",
    currentStatus: "Absent",
    requestedStatus: "Present",
    reason: "Forgot to punch in — was working from the client site all day.",
    status: "Pending",
    siteId: "site-1",
    appliedOn: "2024-06-19",
  },
  {
    id: "reg-2",
    employeeId: "EMP003",
    employee: "Priya Singh",
    date: "2024-05-20",
    currentStatus: "Half Day",
    requestedStatus: "Present",
    reason: "Biometric device was down in the evening; worked full day.",
    status: "Approved",
    siteId: "site-2",
    appliedOn: "2024-05-21",
    approverId: "EMP002",
    approverName: "Rohit Sharma",
    decidedOn: "2024-05-22",
  },
  {
    id: "reg-3",
    employeeId: "EMP006",
    employee: "Vikram Desai",
    date: "2024-06-20",
    currentStatus: "Absent",
    requestedStatus: "Present",
    reason: "System didn't capture my biometric punch — security desk has the visitor log entry.",
    status: "Pending",
    siteId: "site-2",
    appliedOn: "2024-06-21",
  },
  {
    id: "reg-4",
    employeeId: "EMP005",
    employee: "Sneha Kapoor",
    date: "2024-05-15",
    currentStatus: "Absent",
    requestedStatus: "Present",
    reason: "Worked from home due to a family emergency.",
    status: "Rejected",
    siteId: "site-3",
    appliedOn: "2024-05-16",
    approverId: "EMP004",
    approverName: "Neha Verma",
    decisionReason: "No WFH approval on file for that date — please get prior sign-off next time.",
    decidedOn: "2024-05-17",
  },
  {
    id: "reg-5",
    employeeId: "EMP009",
    employee: "Anjali Kumari",
    date: "2024-06-19",
    currentStatus: "Half Day",
    requestedStatus: "Present",
    reason: "Client call ran past the half-day cutoff; was online the rest of the day.",
    status: "Pending",
    siteId: "site-4",
    appliedOn: "2024-06-20",
  },
];
